// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApp.Data;

namespace webApp.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    partial class MyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("webApp.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Dish");

                    b.Property<int>("MinutesToPrepare");

                    b.Property<int>("QualityStars");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new { RecipeId = 1, Description = "Boil water and add tea", Dish = "Tea", MinutesToPrepare = 3, QualityStars = 1 },
                        new { RecipeId = 2, Description = "Boil water. Add coffe and sugar", Dish = "Coffe", MinutesToPrepare = 5, QualityStars = 2 },
                        new { RecipeId = 3, Description = "Boil water. Add coffe. Add milk. Add sugar", Dish = "Caffe Latte", MinutesToPrepare = 7, QualityStars = 3 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
